"""DCGM / NVIDIA GPU reserved alert codes for Keep catalog + provider-mock setup.

Source inventory:
  https://docs.nvidia.com/datacenter/dcgm/latest/reference/dcgm-exporter-metrics.html
  https://docs.nvidia.com/datacenter/dcgm/latest/reference/field-identifiers.html
  https://docs.nvidia.com/datacenter/dcgm/latest/reference/diagnostics/plugins/index.html
  https://docs.nvidia.com/datacenter/dcgm/latest/reference/diagnostics/errors.html
"""

from __future__ import annotations

DCGM_DOCS_URL = (
    "https://docs.nvidia.com/datacenter/dcgm/latest/reference/"
    "dcgm-exporter-metrics.html"
)
DCGM_DIAG_DOCS_URL = (
    "https://docs.nvidia.com/datacenter/dcgm/latest/reference/diagnostics/"
    "plugins/index.html"
)
DCGM_DIAG_ERRORS_URL = (
    "https://docs.nvidia.com/datacenter/dcgm/latest/reference/diagnostics/"
    "errors.html"
)

# Codes that the VictoriaMetrics GPU remediate demo fires and may auto-run.
DEMO_AUTO_RUN_CODES = frozenset(
    {
        "DCGM_FI_DEV_GPU_TEMP",
        "DCGM_FI_DEV_FB_USED",
        "DCGM_FI_DEV_XID_ERRORS",
        "DCGM_FI_DEV_ECC_DBE_VOL_TOTAL",
        "DCGM_FI_DEV_THERMAL_VIOLATION",
        "DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL",
        "DCGM_FI_DEV_POWER_USAGE",
        "DCGM_EXP_GPU_HEALTH_STATUS",
    }
)


def _entry(
    code: str,
    name: str,
    description: str,
    *extra_tags: str,
    bucket: str = "exporter-default",
    runbook_url: str | None = None,
) -> dict:
    tags = ["nvidia", "dcgm", bucket, *extra_tags]
    # Preserve order, drop dupes.
    seen: set[str] = set()
    ordered: list[str] = []
    for tag in tags:
        tag = tag.strip().lower()
        if tag and tag not in seen:
            seen.add(tag)
            ordered.append(tag)
    return {
        "code": code,
        "name": name,
        "description": description,
        "runbook_url": runbook_url or DCGM_DOCS_URL,
        "tags": ordered,
        "disabled": False,
    }


# Shipped default + optional + exporter-owned metrics from DCGM Exporter docs.
# Label-only identity fields are included so the catalog can map them if rules
# ever fire; they are tagged ``label``.
CODES: tuple[dict, ...] = (
    # --- Shipped default metrics ---
    _entry(
        "DCGM_FI_DEV_SM_CLOCK",
        "DCGM SM clock",
        "GPU SM clock frequency (MHz).",
        "clock",
        "util",
    ),
    _entry(
        "DCGM_FI_DEV_MEM_CLOCK",
        "DCGM memory clock",
        "GPU memory clock frequency (MHz).",
        "clock",
        "memory",
    ),
    _entry(
        "DCGM_FI_DEV_MEMORY_TEMP",
        "DCGM memory temperature",
        "GPU memory temperature in Celsius.",
        "thermal",
        "memory",
    ),
    _entry(
        "DCGM_FI_DEV_GPU_TEMP",
        "DCGM GPU temperature",
        "GPU temperature in Celsius. Alert when above operational threshold.",
        "thermal",
    ),
    _entry(
        "DCGM_FI_DEV_POWER_USAGE",
        "DCGM board power",
        "GPU board power draw in watts.",
        "power",
    ),
    _entry(
        "DCGM_FI_DEV_TOTAL_ENERGY_CONSUMPTION",
        "DCGM total energy",
        "Cumulative energy consumption for the GPU.",
        "power",
    ),
    _entry(
        "DCGM_FI_PROF_PCIE_TX_BYTES",
        "DCGM PCIe TX bytes",
        "Profiling: PCIe transmit throughput.",
        "pcie",
        "profiling",
    ),
    _entry(
        "DCGM_FI_PROF_PCIE_RX_BYTES",
        "DCGM PCIe RX bytes",
        "Profiling: PCIe receive throughput.",
        "pcie",
        "profiling",
    ),
    _entry(
        "DCGM_FI_DEV_PCIE_REPLAY_COUNTER",
        "DCGM PCIe replay total",
        "PCIe replay counter — rising values indicate link issues.",
        "pcie",
        "error",
    ),
    _entry(
        "DCGM_FI_DEV_GPU_UTIL",
        "DCGM GPU utilization",
        "GPU utilization ratio.",
        "util",
    ),
    _entry(
        "DCGM_FI_DEV_MEM_COPY_UTIL",
        "DCGM memory copy utilization",
        "Memory copy engine utilization.",
        "memory",
        "util",
    ),
    _entry(
        "DCGM_FI_DEV_ENC_UTIL",
        "DCGM encoder utilization",
        "Video encoder utilization.",
        "util",
    ),
    _entry(
        "DCGM_FI_DEV_DEC_UTIL",
        "DCGM decoder utilization",
        "Video decoder utilization.",
        "util",
    ),
    _entry(
        "DCGM_FI_DEV_XID_ERRORS",
        "DCGM XID error",
        "NVIDIA XID error reported by DCGM. Value is the XID code.",
        "xid",
        "error",
        "health",
    ),
    _entry(
        "DCGM_FI_DEV_FB_FREE",
        "DCGM framebuffer free",
        "Free framebuffer memory.",
        "memory",
    ),
    _entry(
        "DCGM_FI_DEV_FB_USED",
        "DCGM framebuffer used",
        "Used framebuffer memory. Alert when near capacity.",
        "memory",
    ),
    _entry(
        "DCGM_FI_DEV_FB_RESERVED",
        "DCGM framebuffer reserved",
        "Reserved framebuffer memory.",
        "memory",
    ),
    _entry(
        "DCGM_FI_DEV_NVLINK_BANDWIDTH_TOTAL",
        "DCGM NVLink throughput total",
        "Total NVLink throughput.",
        "nvlink",
    ),
    _entry(
        "DCGM_FI_DEV_VGPU_LICENSE_STATUS",
        "DCGM vGPU license status",
        "vGPU license status for the device.",
        "vgpu",
        "health",
    ),
    _entry(
        "DCGM_FI_DEV_UNCORRECTABLE_REMAPPED_ROWS",
        "DCGM uncorrectable remapped rows",
        "Uncorrectable row-remap total.",
        "ecc",
        "memory",
        "error",
    ),
    _entry(
        "DCGM_FI_DEV_CORRECTABLE_REMAPPED_ROWS",
        "DCGM correctable remapped rows",
        "Correctable row-remap total.",
        "ecc",
        "memory",
    ),
    _entry(
        "DCGM_FI_DEV_ROW_REMAP_FAILURE",
        "DCGM row remap failure",
        "Row remap failed on the GPU.",
        "ecc",
        "memory",
        "error",
        "health",
    ),
    _entry(
        "DCGM_FI_DRIVER_VERSION",
        "DCGM driver version",
        "NVIDIA driver version label (identity / mapping).",
        "label",
        bucket="exporter-default",
    ),
    _entry(
        "DCGM_FI_PROF_GR_ENGINE_ACTIVE",
        "DCGM graphics engine util",
        "Profiling: graphics engine utilization ratio.",
        "profiling",
        "util",
    ),
    _entry(
        "DCGM_FI_PROF_PIPE_TENSOR_ACTIVE",
        "DCGM tensor util",
        "Profiling: tensor pipe utilization ratio.",
        "profiling",
        "util",
    ),
    _entry(
        "DCGM_FI_PROF_DRAM_ACTIVE",
        "DCGM DRAM util",
        "Profiling: DRAM utilization ratio.",
        "profiling",
        "memory",
        "util",
    ),
    # --- Shipped optional metrics ---
    _entry(
        "DCGM_FI_DEV_POWER_VIOLATION",
        "DCGM power violation",
        "Time spent in power violation.",
        "power",
        "violation",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_THERMAL_VIOLATION",
        "DCGM thermal violation",
        "Time spent in thermal violation / throttle.",
        "thermal",
        "violation",
        "throttle",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_SYNC_BOOST_VIOLATION",
        "DCGM sync boost violation",
        "Sync boost violation counter.",
        "violation",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_BOARD_LIMIT_VIOLATION",
        "DCGM board limit violation",
        "Board limit violation counter.",
        "power",
        "violation",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_LOW_UTIL_VIOLATION",
        "DCGM low util violation",
        "Low utilization violation counter.",
        "util",
        "violation",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_RELIABILITY_VIOLATION",
        "DCGM reliability violation",
        "Reliability violation counter.",
        "health",
        "violation",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_ECC_SBE_VOL_TOTAL",
        "DCGM ECC SBE volatile total",
        "Volatile single-bit ECC errors.",
        "ecc",
        "memory",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_ECC_DBE_VOL_TOTAL",
        "DCGM ECC DBE volatile total",
        "Volatile double-bit (uncorrectable) ECC errors.",
        "ecc",
        "memory",
        "error",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_ECC_SBE_AGG_TOTAL",
        "DCGM ECC SBE aggregate total",
        "Aggregate single-bit ECC errors.",
        "ecc",
        "memory",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_ECC_DBE_AGG_TOTAL",
        "DCGM ECC DBE aggregate total",
        "Aggregate double-bit ECC errors.",
        "ecc",
        "memory",
        "error",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_RETIRED_SBE",
        "DCGM retired pages SBE",
        "Pages retired due to single-bit errors.",
        "ecc",
        "memory",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_RETIRED_DBE",
        "DCGM retired pages DBE",
        "Pages retired due to double-bit errors.",
        "ecc",
        "memory",
        "error",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_RETIRED_PENDING",
        "DCGM retired pages pending",
        "Pages pending retirement.",
        "ecc",
        "memory",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_NVLINK_CRC_FLIT_ERROR_COUNT_TOTAL",
        "DCGM NVLink CRC flit errors",
        "NVLink CRC flit error total.",
        "nvlink",
        "error",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_NVLINK_CRC_DATA_ERROR_COUNT_TOTAL",
        "DCGM NVLink CRC data errors",
        "NVLink CRC data error total.",
        "nvlink",
        "error",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_NVLINK_REPLAY_ERROR_COUNT_TOTAL",
        "DCGM NVLink replay errors",
        "NVLink replay error total.",
        "nvlink",
        "error",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_NVLINK_RECOVERY_ERROR_COUNT_TOTAL",
        "DCGM NVLink recovery errors",
        "NVLink recovery error total.",
        "nvlink",
        "error",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_NVLINK_BANDWIDTH_L0",
        "DCGM NVLink throughput L0",
        "NVLink throughput on link 0.",
        "nvlink",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_NVML_VERSION",
        "DCGM NVML version",
        "NVML version label.",
        "label",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_BRAND",
        "DCGM GPU brand",
        "GPU brand label.",
        "label",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_SERIAL",
        "DCGM board serial",
        "Board serial label.",
        "label",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_OEM_INFOROM_VER",
        "DCGM InfoROM OEM version",
        "InfoROM OEM version label.",
        "label",
        "inforom",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_ECC_INFOROM_VER",
        "DCGM InfoROM ECC version",
        "InfoROM ECC version label.",
        "label",
        "inforom",
        "ecc",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_POWER_INFOROM_VER",
        "DCGM InfoROM power version",
        "InfoROM power version label.",
        "label",
        "inforom",
        "power",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_INFOROM_IMAGE_VER",
        "DCGM InfoROM image version",
        "InfoROM image version label.",
        "label",
        "inforom",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_DEV_VBIOS_VERSION",
        "DCGM VBIOS version",
        "VBIOS version label.",
        "label",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_SM_ACTIVE",
        "DCGM SM util",
        "Profiling: SM utilization ratio.",
        "profiling",
        "util",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_SM_OCCUPANCY",
        "DCGM SM occupancy",
        "Profiling: SM occupancy ratio.",
        "profiling",
        "util",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_PIPE_FP64_ACTIVE",
        "DCGM FP64 util",
        "Profiling: FP64 pipe utilization.",
        "profiling",
        "util",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_PIPE_FP32_ACTIVE",
        "DCGM FP32 util",
        "Profiling: FP32 pipe utilization.",
        "profiling",
        "util",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_PIPE_FP16_ACTIVE",
        "DCGM FP16 util",
        "Profiling: FP16 pipe utilization.",
        "profiling",
        "util",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_SM_CYCLES_ELAPSED_TOTAL",
        "DCGM SM cycles elapsed",
        "Profiling: SM cycles elapsed total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_SM_CYCLES_ACTIVE_TOTAL",
        "DCGM SM cycles active",
        "Profiling: SM cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_MMA_CYCLES_ACTIVE_TOTAL",
        "DCGM MMA cycles active",
        "Profiling: MMA cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_DMMA_CYCLES_ACTIVE_TOTAL",
        "DCGM DMMA cycles active",
        "Profiling: DMMA cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_HMMA_CYCLES_ACTIVE_TOTAL",
        "DCGM HMMA cycles active",
        "Profiling: HMMA cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_IMMA_CYCLES_ACTIVE_TOTAL",
        "DCGM IMMA cycles active",
        "Profiling: IMMA cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_DFMA_CYCLES_ACTIVE_TOTAL",
        "DCGM DFMA cycles active",
        "Profiling: DFMA cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_PCIE_TX_BYTES_TOTAL",
        "DCGM PCIe TX bytes total",
        "Profiling: cumulative PCIe TX bytes.",
        "pcie",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_PCIE_RX_BYTES_TOTAL",
        "DCGM PCIe RX bytes total",
        "Profiling: cumulative PCIe RX bytes.",
        "pcie",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_INT_CYCLES_ACTIVE_TOTAL",
        "DCGM INT cycles active",
        "Profiling: INT cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_FP64_CYCLES_ACTIVE_TOTAL",
        "DCGM FP64 cycles active",
        "Profiling: FP64 cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_FP32_CYCLES_ACTIVE_TOTAL",
        "DCGM FP32 cycles active",
        "Profiling: FP32 cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    _entry(
        "DCGM_FI_PROF_FP16_CYCLES_ACTIVE_TOTAL",
        "DCGM FP16 cycles active",
        "Profiling: FP16 cycles active total.",
        "profiling",
        bucket="exporter-optional",
    ),
    # --- Exporter-owned metrics ---
    _entry(
        "DCGM_EXP_CLOCK_EVENTS_COUNT",
        "DCGM clock events count",
        "Windowed count of active clock-event reasons (throttle / power / thermal).",
        "throttle",
        "clock",
        "thermal",
        "power",
        bucket="exporter-owned",
    ),
    _entry(
        "DCGM_EXP_CLOCK_EVENTS_TOTAL",
        "DCGM clock events total",
        "Cumulative inactive-to-active transitions per clock_event reason.",
        "throttle",
        "clock",
        bucket="exporter-owned",
    ),
    _entry(
        "DCGM_EXP_XID_ERRORS_COUNT",
        "DCGM XID errors count",
        "Windowed XID sample count grouped by xid label.",
        "xid",
        "error",
        "health",
        bucket="exporter-owned",
    ),
    _entry(
        "DCGM_EXP_XID_ERRORS_TOTAL",
        "DCGM XID errors total",
        "Cumulative nonzero XID observations grouped by xid.",
        "xid",
        "error",
        "health",
        bucket="exporter-owned",
    ),
    _entry(
        "DCGM_EXP_GPU_HEALTH_STATUS",
        "DCGM GPU health status",
        "Exporter health watch result (0=PASS, 10=WARN, 20=FAIL) per health_watch.",
        "health",
        "error",
        bucket="exporter-owned",
    ),
    _entry(
        "DCGM_EXP_P2P_STATUS",
        "DCGM P2P status",
        "GPU P2P / NVLink peer status matrix entry.",
        "nvlink",
        "health",
        bucket="exporter-owned",
    ),
    # --- Active diagnostics plugins (dcgmi diag) ---
    _entry(
        "DCGM_DIAG_SOFTWARE",
        "DCGM diag: software deployment",
        "Level-1 software/deployment checks (libraries, device access, conflicting processes).",
        "diag",
        "suite-1",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_CONTEXT_CREATE",
        "DCGM diag: context create",
        "Verify CUDA context creation on the target GPU.",
        "diag",
        "cuda",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_MEMORY",
        "DCGM diag: GPU memory",
        "Framebuffer allocation, patterns, cache, and observed memory errors.",
        "diag",
        "memory",
        "suite-2",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_PCIE",
        "DCGM diag: PCIe bandwidth",
        "PCIe / P2P bandwidth, latency, link state, and error counters.",
        "diag",
        "pcie",
        "suite-2",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_DIAGNOSTIC",
        "DCGM diag: compute stress",
        "Sustained matrix operations exercising compute and framebuffer paths.",
        "diag",
        "compute",
        "suite-3",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_MEMORY_BANDWIDTH",
        "DCGM diag: memory bandwidth",
        "Local framebuffer bandwidth vs device threshold.",
        "diag",
        "memory",
        "suite-3",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_TARGETED_STRESS",
        "DCGM diag: targeted stress",
        "Controlled GEMM workload sustaining a requested compute rate.",
        "diag",
        "compute",
        "suite-3",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_TARGETED_POWER",
        "DCGM diag: targeted power",
        "Drive GPU toward a requested power level and monitor conditions.",
        "diag",
        "power",
        "suite-3",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_NVBANDWIDTH",
        "DCGM diag: NVBandwidth",
        "Validate GPU copy paths over NVLink and PCIe.",
        "diag",
        "nvlink",
        "suite-3",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_MEMTEST",
        "DCGM diag: memtest",
        "Extended GPU memory address/bit/coupling/retention patterns (suite 4).",
        "diag",
        "memory",
        "suite-4",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    _entry(
        "DCGM_DIAG_PULSE_TEST",
        "DCGM diag: pulse test",
        "Rapid power/current swings to expose board delivery instability (suite 4).",
        "diag",
        "power",
        "suite-4",
        bucket="diag-plugin",
        runbook_url=DCGM_DIAG_DOCS_URL,
    ),
    # --- Diagnostic finding codes (severity → Keep action) ---
    _entry(
        "DCGM_FR_FAULTY_MEMORY",
        "DCGM FR: faulty memory",
        "Diagnostic found faulty GPU memory. Severity ISOLATE — cordon, do not auto-reset.",
        "diag",
        "isolate",
        "memory",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_VOLATILE_DBE_DETECTED",
        "DCGM FR: volatile DBE",
        "Uncorrectable double-bit ECC during diagnostics. Severity ISOLATE.",
        "diag",
        "isolate",
        "memory",
        "ecc",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_PCI_REPLAY_RATE",
        "DCGM FR: PCIe replay rate",
        "Excessive PCIe replay rate. Severity ISOLATE.",
        "diag",
        "isolate",
        "pcie",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_NVLINK_ERROR_THRESHOLD",
        "DCGM FR: NVLink error threshold",
        "NVLink error threshold exceeded. Severity ISOLATE.",
        "diag",
        "isolate",
        "nvlink",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_PENDING_PAGE_RETIREMENTS",
        "DCGM FR: pending page retirements",
        "Pending page retirements require GPU reset. Severity RESET.",
        "diag",
        "reset",
        "memory",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_ROW_REMAP_FAILURE",
        "DCGM FR: row remap failure",
        "Row remap failure; GPU reset required. Severity RESET.",
        "diag",
        "reset",
        "memory",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_THERMAL_VIOLATIONS",
        "DCGM FR: thermal violations",
        "Thermal violations observed during diagnostics. Severity MONITOR.",
        "diag",
        "monitor",
        "thermal",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_BAD_CUDA_ENV",
        "DCGM FR: bad CUDA environment",
        "CUDA environment/config problem. Severity CONFIG — fix software, not hardware.",
        "diag",
        "config",
        "cuda",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_LOW_BANDWIDTH",
        "DCGM FR: low bandwidth",
        "PCIe/NVLink bandwidth below threshold. Severity TRIAGE.",
        "diag",
        "triage",
        "pcie",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
    _entry(
        "DCGM_FR_XID_ERROR",
        "DCGM FR: XID error",
        "XID observed during diagnostics. Severity TRIAGE.",
        "diag",
        "triage",
        "xid",
        bucket="diag-error",
        runbook_url=DCGM_DIAG_ERRORS_URL,
    ),
)

