{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "synthetic-checks.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: synthetic-checks
{{- end }}
