#!/usr/bin/env bash
# Run Keep UI on the host against the kind local-dev namespace (keep).
# Port-forwards Keep API (:8080) and websocket (:6001) if kind NodePorts are not mapped.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
UI_DIR="${ROOT}/keep-ui"
ENV_FILE="${UI_DIR}/.env.k8s.local"
KUBECTL="${KUBECTL:-kubectl}"
DEV_NAMESPACE="${DEV_NAMESPACE:-keep}"
PF_DIR="${TMPDIR:-/tmp}/opsengine-k8s-pf"

mkdir -p "$PF_DIR"

tcp_open() {
  local port="$1"
  python3 - "$port" <<'PY'
import socket, sys
port = int(sys.argv[1])
try:
    socket.create_connection(("127.0.0.1", port), 2).close()
except OSError:
    raise SystemExit(1)
PY
}

http_ok() {
  curl -sf --max-time 3 "$1" >/dev/null 2>&1
}

ensure_port_forward() {
  local name="$1" svc="$2" local_port="$3" remote_port="$4" health_url="${5:-}"
  if [[ -n "$health_url" ]]; then
    if http_ok "$health_url"; then
      echo "    ${name}  http://localhost:${local_port}  (already up)"
      return 0
    fi
  elif tcp_open "$local_port"; then
    echo "    ${name}  localhost:${local_port}  (already up)"
    return 0
  fi

  if [[ -f "${PF_DIR}/${name}.pid" ]]; then
    kill "$(cat "${PF_DIR}/${name}.pid")" 2>/dev/null || true
    rm -f "${PF_DIR}/${name}.pid"
  fi

  echo "    ${name}  port-forward svc/${svc} ${local_port}:${remote_port}"
  nohup $KUBECTL -n "$DEV_NAMESPACE" port-forward "svc/${svc}" "${local_port}:${remote_port}" \
    >"${PF_DIR}/${name}.log" 2>&1 &
  echo $! >"${PF_DIR}/${name}.pid"

  local i
  for i in $(seq 1 30); do
    if [[ -n "$health_url" ]]; then
      http_ok "$health_url" && return 0
    else
      tcp_open "$local_port" && return 0
    fi
    sleep 1
  done
  echo "timeout waiting for ${name} on localhost:${local_port}" >&2
  cat "${PF_DIR}/${name}.log" >&2 || true
  return 1
}

write_ui_env() {
  cat >"$ENV_FILE" <<EOF
# Generated by scripts/k8s_ui.sh — kind local-dev (namespace ${DEV_NAMESPACE})
AUTH_TYPE=DB
API_URL=http://localhost:8080
API_URL_CLIENT=http://localhost:8080
PUSHER_HOST=localhost
PUSHER_PORT=6001
PUSHER_APP_KEY=keepappkey
NEXTAUTH_URL=http://localhost:3000
NEXTAUTH_SECRET=k8s-dev-nextauth-secret
AUTH_SECRET=k8s-dev-nextauth-secret
AUTH_DEBUG=false
NEXT_TELEMETRY_DISABLED=1
EOF
}

print_urls() {
  cat <<'EOF'

============================================================
  OpsEngine kind local-dev — access URLs
============================================================
  Keep UI            http://localhost:3000   (admin / admin)
  Keep API           http://localhost:8080
  API health         http://localhost:8080/healthcheck
  API docs           http://localhost:8080/docs
  Websocket          http://localhost:6001
  Provider mock      http://localhost:8099
  Temporal UI        http://localhost:8233
============================================================

EOF
}

if [[ ! -d "${UI_DIR}/node_modules" ]]; then
  echo "Installing keep-ui dependencies..."
  (cd "$UI_DIR" && npm install)
fi

echo "==> Port-forward / host access (namespace ${DEV_NAMESPACE})"
ensure_port_forward backend keep-backend 8080 8080 "http://127.0.0.1:8080/healthcheck"
ensure_port_forward websocket keep-websocket 6001 6001
ensure_port_forward mock provider-mock 8099 8099 "http://127.0.0.1:8099/api/health"
ensure_port_forward temporal temporal 8233 8233 "http://127.0.0.1:8233"

if ! http_ok "http://127.0.0.1:8080/healthcheck"; then
  echo "Keep API is not healthy on http://localhost:8080/healthcheck" >&2
  echo "Check: kubectl -n ${DEV_NAMESPACE} get pods,svc" >&2
  exit 1
fi

write_ui_env
set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
set +a

# Exported values win over keep-ui/.env.local so AUTH_TYPE stays DB for kind.
export AUTH_TYPE API_URL API_URL_CLIENT
export PUSHER_HOST PUSHER_PORT PUSHER_APP_KEY
export NEXTAUTH_URL NEXTAUTH_SECRET AUTH_SECRET AUTH_DEBUG NEXT_TELEMETRY_DISABLED

print_urls
echo "UI env: ${ENV_FILE}  (API_URL=${API_URL}  AUTH_TYPE=${AUTH_TYPE})"
echo "Ctrl+C stops the UI; the kind cluster and port-forwards stay up."
echo ""

cd "$UI_DIR"
exec npm run dev
